clean:
	rm -f level-4.db

hack:
	poetry run python -m unittest hack.py

test1:
	poetry run python -m unittest tests.TestDatabase.test_1

test2:
	poetry run python -m unittest tests.TestDatabase.test_2

test3:
	poetry run python -m unittest tests.TestDatabase.test_3

test4:
	poetry run python -m unittest tests.TestDatabase.test_4

test5:
	poetry run python -m unittest tests.TestDatabase.test_5

test6:
	poetry run python -m unittest tests.TestDatabase.test_6

tests:
	poetry run python -m unittest tests.py
